Repository stolostron/thanos, pull requests merged in 2024-08, with the labels that each got.

#147 chore: Add schedule to update Konflux files
  renovate.json
Labels: lgtm, approved

#148 fix(KONFLUX-3663): format PipelineRun files and upload SAST results
  .tekton/thanos-acm-210-pull-request.yaml
  .tekton/thanos-acm-210-push.yaml
Labels: ok-to-test

#149 fix(KONFLUX-3663): format PipelineRun files and upload SAST results
  .tekton/thanos-acm-211-pull-request.yaml
  .tekton/thanos-acm-211-push.yaml
Labels: lgtm, ok-to-test
