Repository stolostron/thanos, pull requests merged in 2025-04, with the labels that each got.

#168 Add new SAST tasks to Konflux pipelines
  .tekton/thanos-acm-214-pull-request.yaml
  .tekton/thanos-acm-214-push.yaml
Labels: lgtm, approved, ok-to-test

#172 [release-2.11] Bump github.com/golang-jwt/jwt/v5 to 5.2.2
  go.mod
  go.sum
Labels: lgtm

#173 [release-2.10] Bump github.com/golang-jwt/jwt/v5 to 5.2.2
  go.mod
  go.sum
Labels: lgtm

#174 [release-2.9] Bump github.com/golang-jwt/jwt/v5 to 5.2.2
  go.mod
  go.sum
Labels: lgtm

#175 Update renovate.json
  renovate.json
Labels: lgtm, approved
